<?php

/**
 * Implements hook_menu().
 */
function commerce_omnipay_menu() {
  $items = array();
  $items['admin/commerce/payment-gateways'] = array(
    'title' => 'Payment Gateways',
    'page callback' => 'commerce_omnipay_settings_page',
    'access arguments' => array('configure store'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/commerce_omnipay.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_omnipay_commerce_payment_method_info() {
  $payment_methods['omnipay'] = array(
    'base' => 'commerce_omnipay_omnipay',
    'title' => t('Omnipay'),
    'short_title' => t('Omnipay'),
    'description' => t('Omnipay'),
    'terminal' => FALSE,
    'offsite' => FALSE,
    'offsite_autoredirect' => FALSE,
    'file' => 'includes/commerce_omnipay.payment_method.inc',

  );
  return $payment_methods;
}

/**
 * List supported gateways.
 * @return array
 */
function commerce_omnipay_supported_gateways() {
  $gateways = array();

  $gateways['stripe'] = array(
    'label' => "Stripe",
    'gateway' => "Stripe",
    'description' => "Stripe",
    'website' => "http://stripe.com",
  );

  $gateways['PayPal_Pro'] = array(
    'label' => "PayPal Pro",
    'gateway' => "PayPal_Pro",
    'description' => "Paypal",
    'website' => "http://stripe.com",
  );

  $gateways['WorldPay'] = array(
    'label' => "PayPal",
    'gateway' => "PayPal",
    'description' => "Stripe",
    'website' => "http://stripe.com",
  );

  $gateways['WorldPay'] = array(
    'label' => "WorldPay",
    'gateway' => "WorldPay",
    'description' => "Stripe",
    'website' => "http://stripe.com",
  );

  $gateways['AuthorizeNet_AIM'] = array(
    'label' => "AuthorizeNet_AIM",
    'gateway' => "AuthorizeNet_AIM",
    'description' => "Stripe",
    'website' => "http://stripe.com",
  );

  drupal_alter('commerce_omnipay_gateways', $gateways);

  return $gateways;

}

function commerce_omnipay_get_gateway_settings($gateway) {
  $settings = variable_get("commerce_omnipay_gateway_settings_" . $gateway, array());
  drupal_alter('commerce_omnipay_settings', $settings, $gateway);
  return $settings;
}

function commerce_omnipay_set_gateway_settings($gateway, $settings) {
  return variable_set("commerce_omnipay_gateway_settings_" . $gateway, $settings);
}